# fly.toml app configuration file generated for be-capernam on 2025-05-28T16:02:14-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'be-capernam'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
