export const teamLogos: Record<string, string> = {
    "49ers": "https://static.www.nfl.com/image/private/f_auto/league/fk3naqzippm49yrh4twi",
    "Bears": "https://static.www.nfl.com/image/private/f_auto/league/zd5g2rzvydzaxlrcpiu1",
    "Bengals": "https://static.www.nfl.com/image/private/f_auto/league/xwpxj7amc9wzzuepu7jc",
    "Bills": "https://static.www.nfl.com/image/private/f_auto/league/ysyb6thxqfhhmkgwxvfp",
    "Broncos": "https://static.www.nfl.com/image/private/f_auto/league/zh2p6lmzqsk9xzv5sdpd",
    "Browns": "https://static.www.nfl.com/image/private/f_auto/league/n5zlm2p6fqpnqgf9zjqr",
    "Buccaneers": "https://static.www.nfl.com/image/private/f_auto/league/clpxmvhdrtss8aidakog",
    "Cardinals": "https://static.www.nfl.com/image/private/f_auto/league/mhr3ymgcsvpnkgg3oqp0",
    "Chargers": "https://static.www.nfl.com/image/private/f_auto/league/rihpdlgszjsxshmhsm53",
    "Chiefs": "https://static.www.nfl.com/image/private/f_auto/league/rg8wypdaatstpdihvdvq",
    "Colts": "https://static.www.nfl.com/image/private/f_auto/league/yy8feykcffckbqy22y7w",
    "Commanders": "https://static.www.nfl.com/image/private/f_auto/league/wo7ua6i5bvjuxomj6mei",
    "Cowboys": "https://static.www.nfl.com/image/private/f_auto/league/arpw5iuvt7kwsxgsdxz5",
    "Dolphins": "https://static.www.nfl.com/image/private/f_auto/league/gcrp8tzbaov80yujrqf7",
    "Eagles": "https://static.www.nfl.com/image/private/f_auto/league/f0iqah8bz5gsjpkpkaji",
    "Falcons": "https://static.www.nfl.com/image/private/f_auto/league/tzivj6ehwqiokkufxv4r",
    "Giants": "https://static.www.nfl.com/image/private/f_auto/league/avpzfghkoxlqfjyreqr5",
    "Jaguars": "https://static.www.nfl.com/image/private/f_auto/league/z7zkwbywqd8bdyugyzsr",
    "Jets": "https://static.www.nfl.com/image/private/f_auto/league/jbyed1y4rh5lsqheggcg",
    "Lions": "https://static.www.nfl.com/image/private/f_auto/league/fblq8k5rvvhduzvez6m4",
    "Packers": "https://static.www.nfl.com/image/private/f_auto/league/qxxvzsn6ydn2ieefj6t7",
    "Panthers": "https://static.www.nfl.com/image/private/f_auto/league/mvjusyozmxqgxu7fvo2z",
    "Patriots": "https://static.www.nfl.com/image/private/f_auto/league/qxxvzsn6ydn2ieefj6t7",
    "Raiders": "https://static.www.nfl.com/image/private/f_auto/league/xxqdcqhzutkz3cdxigjg",
    "Rams": "https://static.www.nfl.com/image/private/f_auto/league/ho2sdnrbmwd9v0vgrsua",
    "Ravens": "https://static.www.nfl.com/image/private/f_auto/league/rsukvwjjqibcxi9k19pb",
    "Saints": "https://static.www.nfl.com/image/private/f_auto/league/hy0eyy1i8vxthkfqkhnl",
    "Seahawks": "https://static.www.nfl.com/image/private/f_auto/league/ucibz7gsyc0ckpp9ut7j",
    "Steelers": "https://static.www.nfl.com/image/private/f_auto/league/zoz99g0t1zhstbxybgwe",
    "Texans": "https://static.www.nfl.com/image/private/f_auto/league/pwytkr4v2zzq1tihkx8l",
    "Titans": "https://static.www.nfl.com/image/private/f_auto/league/o9yoidx8r2vfb1bgcpvw",
    "Vikings": "https://static.www.nfl.com/image/private/f_auto/league/waasibnu6y4pplsjlvsa",
  };
  